apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: restaurant-landing-page
  namespace: flux-system
spec:
  interval: 1m
  path: "./clusters/my-cluster/restaurant-landing"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client

