apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: restaurant
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: restaurant
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: Flux
        email: flux@example.com
    push:
      branch: main
  update:
    strategy: Setters

