apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: restaurant
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/vedastuss/restaurant-kustomize.git
  ref:
    branch: main

