apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: restaurant-landing
spec:
  interval: 5m
  path: ./apps/restaurant
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
