apiVersion: v1
kind: Service
metadata:
  name: restaurant-landing
spec:
  type: NodePort
  selector:
    app: restaurant-landing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080

